local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[408070] = {
		readable = "Sandsparkle Clam",
		model = 196998,
		text = {
			en = "Sandsparkle Clam",
			es = "Almeja brillarena",
			mx = "[Sandsparkle Clam]",
			de = "Sandschimmermuschel",
			fr = "Palourde Scintisable",
			it = "Ostrica Splendisabbia",
			pt = "Marisco Reluzareia",
			ru = "Моллюск Блестящего Песка",
			ko = "[Sandsparkle Clam]",
			cn = "[Sandsparkle Clam]",
			tw = "沙耀蚌殼",
		},
	},
	[523388] = {
		readable = "Maraad's Meditation Crystal",
		model = 1108688,
		text = {
			en = "Maraad's Meditation Crystal",
			es = "Cristal de meditación de Maraad",
			mx = "[Maraad's Meditation Crystal]",
			de = "Maraads Meditationskristall",
			fr = "Cristal de méditation de Maraad",
			it = "[Maraad's Meditation Crystal]",
			pt = "Cristal de Meditação do Maraad",
			ru = "[Maraad's Meditation Crystal]",
			ko = "[Maraad's Meditation Crystal]",
			cn = "[Maraad's Meditation Crystal]",
			tw = "瑪銳德的冥想水晶",
		},
	},
	[525374] = {
		readable = "Stolen Equipment",
		model = 6733832,
		text = {
			en = "Stolen Equipment",
			es = "[Stolen Equipment]",
			mx = "[Stolen Equipment]",
			de = "[Stolen Equipment]",
			fr = "[Stolen Equipment]",
			it = "[Stolen Equipment]",
			pt = "[Stolen Equipment]",
			ru = "[Stolen Equipment]",
			ko = "[Stolen Equipment]",
			cn = "[Stolen Equipment]",
			tw = "[Stolen Equipment]",
		},
	},
	[525891] = {
		readable = "Amani Skinning Knife",
		model = 977082,
		text = {
			en = "Amani Skinning Knife",
			es = "[Amani Skinning Knife]",
			mx = "[Amani Skinning Knife]",
			de = "Kürschnermesser der Amani",
			fr = "[Amani Skinning Knife]",
			it = "[Amani Skinning Knife]",
			pt = "[Amani Skinning Knife]",
			ru = "[Amani Skinning Knife]",
			ko = "[Amani Skinning Knife]",
			cn = "[Amani Skinning Knife]",
			tw = "[Amani Skinning Knife]",
		},
	},
	[525893] = {
		readable = "Amani Tanning Oil",
		model = 936458,
		text = {
			en = "Amani Tanning Oil",
			es = "[Amani Tanning Oil]",
			mx = "[Amani Tanning Oil]",
			de = "[Amani Tanning Oil]",
			fr = "[Amani Tanning Oil]",
			it = "Olio per Tannatura degli Amani",
			pt = "[Amani Tanning Oil]",
			ru = "[Amani Tanning Oil]",
			ko = "[Amani Tanning Oil]",
			cn = "[Amani Tanning Oil]",
			tw = "[Amani Tanning Oil]",
		},
	},
	[525898] = {
		readable = "Artisan's Cover Comb",
		model = 7197588,
		text = {
			en = "Artisan's Cover Comb",
			es = "[Artisan's Cover Comb]",
			mx = "[Artisan's Cover Comb]",
			de = "Abdeckkamm des Kunsthandwerkers",
			fr = "Peigne d’artisanat",
			it = "[Artisan's Cover Comb]",
			pt = "[Artisan's Cover Comb]",
			ru = "[Artisan's Cover Comb]",
			ko = "[Artisan's Cover Comb]",
			cn = "[Artisan's Cover Comb]",
			tw = "[Artisan's Cover Comb]",
		},
	},
	[525899] = {
		readable = "Particularly Enchanting Tablecloth",
		model = 7014302,
		text = {
			en = "Particularly Enchanting Tablecloth",
			es = "Mantel particularmente encantador",
			mx = "[Particularly Enchanting Tablecloth]",
			de = "Besonders bezauberndes Tischtuch",
			fr = "Nappe particulièrement envoûtante",
			it = "Tovaglia Particolarmente Incantevole",
			pt = "Toalha de Mesa Particularmente Encantadora",
			ru = "Скатерть с особыми чарами",
			ko = "[Particularly Enchanting Tablecloth]",
			cn = "[Particularly Enchanting Tablecloth]",
			tw = "特別附魔的桌布",
		},
	},
	[525900] = {
		readable = "Satin Throw Pillow",
		model = 6050854,
		text = {
			en = "Satin Throw Pillow",
			es = "[Satin Throw Pillow]",
			mx = "[Satin Throw Pillow]",
			de = "[Satin Throw Pillow]",
			fr = "[Satin Throw Pillow]",
			it = "[Satin Throw Pillow]",
			pt = "[Satin Throw Pillow]",
			ru = "[Satin Throw Pillow]",
			ko = "[Satin Throw Pillow]",
			cn = "[Satin Throw Pillow]",
			tw = "[Satin Throw Pillow]",
		},
	},
	[525901] = {
		readable = "Book of Sin'dorei Stitches",
		model = 6081188,
		text = {
			en = "Book of Sin'dorei Stitches",
			es = "[Book of Sin'dorei Stitches]",
			mx = "[Book of Sin'dorei Stitches]",
			de = "[Book of Sin'dorei Stitches]",
			fr = "[Book of Sin'dorei Stitches]",
			it = "[Book of Sin'dorei Stitches]",
			pt = "[Book of Sin'dorei Stitches]",
			ru = "[Book of Sin'dorei Stitches]",
			ko = "[Book of Sin'dorei Stitches]",
			cn = "[Book of Sin'dorei Stitches]",
			tw = "[Book of Sin'dorei Stitches]",
		},
	},
	[525902] = {
		readable = "Wooden Weaving Sword",
		model = 7197586,
		text = {
			en = "Wooden Weaving Sword",
			es = "Batidor de madera",
			mx = "[Wooden Weaving Sword]",
			de = "Hölzernes Webschwert",
			fr = "[Wooden Weaving Sword]",
			it = "[Wooden Weaving Sword]",
			pt = "[Wooden Weaving Sword]",
			ru = "[Wooden Weaving Sword]",
			ko = "[Wooden Weaving Sword]",
			cn = "[Wooden Weaving Sword]",
			tw = "[Wooden Weaving Sword]",
		},
	},
	[525903] = {
		readable = "Sin'dorei Outfitter's Ruler",
		model = 4323303,
		text = {
			en = "Sin'dorei Outfitter's Ruler",
			es = "Regla de sastre sin'dorei",
			mx = "[Sin'dorei Outfitter's Ruler]",
			de = "Lineal des Sin'dorei-Ausstatters",
			fr = "Mètre de couture sin’dorei",
			it = "Righello dello Stilista Sin'dorei",
			pt = "Régua do Provedor Sin'dorei",
			ru = "[Sin'dorei Outfitter's Ruler]",
			ko = "[Sin'dorei Outfitter's Ruler]",
			cn = "[Sin'dorei Outfitter's Ruler]",
			tw = "[Sin'dorei Outfitter's Ruler]",
		},
	},
	[525904] = {
		readable = "A Really Nice Curtain",
		model = 6435039,
		text = {
			en = "A Really Nice Curtain",
			es = "Cortinilla preciosa",
			mx = "[A Really Nice Curtain]",
			de = "Ein richtig schöner Vorhang",
			fr = "Très beau rideau",
			it = "Tenda Molto Piacevole",
			pt = "Uma Cortina Bem Legal",
			ru = "Красивая штора",
			ko = "[A Really Nice Curtain]",
			cn = "[A Really Nice Curtain]",
			tw = "頂級窗簾",
		},
	},
	[525905] = {
		readable = "A Child's Stuffy",
		model = 5350798,
		text = {
			en = "A Child's Stuffy",
			es = "Peluchín",
			mx = "[A Child's Stuffy]",
			de = "Ein Stofftier eines Kindes",
			fr = "[A Child's Stuffy]",
		},
	},
})
do ObjectDB[objectID] = objectData; end
