local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[572448] = {
		readable = "Ebon Banner",
		model = 194802,
		text = {
			en = "Ebon Banner",
			es = "Estandarte ébano",
			mx = "[Ebon Banner]",
			de = "Schwarzbanner",
			fr = "Bannière d’ébène",
			it = "Stendardo d'Ebano",
			pt = "Estandarte de Ébano",
			ru = "Черное знамя",
			ko = "칠흑 깃발",
			cn = "[Ebon Banner]",
			tw = "黯黑旌旗",
		},
	},
	[572453] = {
		readable = "Pylon Fragment",
		model = 1327768,
		text = {
			en = "Pylon Fragment",
			es = "Fragmento de pilón",
			mx = "[Pylon Fragment]",
			de = "Pylonfragment",
			fr = "Fragment de pylône",
			it = "Frammento di Pilone",
			pt = "[Pylon Fragment]",
			ru = "Фрагмент пилона",
			ko = "수정탑 파편",
			cn = "晶塔碎片",
			tw = "[Pylon Fragment]",
		},
	},
	[649209] = {
		readable = "Misplaced Ritual Candle",
		model = 5975162,
		text = {
			en = "Misplaced Ritual Candle",
			es = "[Misplaced Ritual Candle]",
			mx = "[Misplaced Ritual Candle]",
			de = "[Misplaced Ritual Candle]",
			fr = "[Misplaced Ritual Candle]",
			it = "[Misplaced Ritual Candle]",
			pt = "[Misplaced Ritual Candle]",
			ru = "[Misplaced Ritual Candle]",
			ko = "[Misplaced Ritual Candle]",
			cn = "[Misplaced Ritual Candle]",
			tw = "[Misplaced Ritual Candle]",
		},
	},
})
do ObjectDB[objectID] = objectData; end
