local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[525919] = {
		readable = "Prestigiously Racked Hide",
		model = 6212431,
		text = {
			en = "Prestigiously Racked Hide",
			es = "[Prestigiously Racked Hide]",
			mx = "Cuero exhibido con prestigio",
			de = "[Prestigiously Racked Hide]",
			fr = "[Prestigiously Racked Hide]",
			it = "Pelle Tesa con Prestigio",
			pt = "[Prestigiously Racked Hide]",
			ru = "[Prestigiously Racked Hide]",
			ko = "[Prestigiously Racked Hide]",
			cn = "[Prestigiously Racked Hide]",
			tw = "[Prestigiously Racked Hide]",
		},
	},
	[525920] = {
		readable = "Ethereal Leatherworking Knife",
		model = 4756264,
		text = {
			en = "Ethereal Leatherworking Knife",
			es = "[Ethereal Leatherworking Knife]",
			mx = "[Ethereal Leatherworking Knife]",
			de = "[Ethereal Leatherworking Knife]",
			fr = "[Ethereal Leatherworking Knife]",
			it = "[Ethereal Leatherworking Knife]",
			pt = "[Ethereal Leatherworking Knife]",
			ru = "[Ethereal Leatherworking Knife]",
			ko = "[Ethereal Leatherworking Knife]",
			cn = "[Ethereal Leatherworking Knife]",
			tw = "[Ethereal Leatherworking Knife]",
		},
	},
	[525921] = {
		readable = "Amani Leatherworker's Tool",
		model = 6125156,
		text = {
			en = "Amani Leatherworker's Tool",
			es = "[Amani Leatherworker's Tool]",
			mx = "[Amani Leatherworker's Tool]",
			de = "[Amani Leatherworker's Tool]",
			fr = "[Amani Leatherworker's Tool]",
			it = "[Amani Leatherworker's Tool]",
			pt = "[Amani Leatherworker's Tool]",
			ru = "[Amani Leatherworker's Tool]",
			ko = "[Amani Leatherworker's Tool]",
			cn = "[Amani Leatherworker's Tool]",
			tw = "[Amani Leatherworker's Tool]",
		},
	},
	[525922] = {
		readable = "Sin'dorei Gem Faceters",
		model = 980101,
		text = {
			en = "Sin'dorei Gem Faceters",
			es = "[Sin'dorei Gem Faceters]",
			mx = "[Sin'dorei Gem Faceters]",
			de = "Edelsteinschleifer der Sin'dorei",
			fr = "[Sin'dorei Gem Faceters]",
			it = "[Sin'dorei Gem Faceters]",
			pt = "[Sin'dorei Gem Faceters]",
			ru = "Син'дорайский огранщик самоцветов",
			ko = "[Sin'dorei Gem Faceters]",
			cn = "[Sin'dorei Gem Faceters]",
			tw = "[Sin'dorei Gem Faceters]",
		},
	},
	[525923] = {
		readable = "Ethereal Gem Pliers",
		model = 948778,
		text = {
			en = "Ethereal Gem Pliers",
			es = "[Ethereal Gem Pliers]",
			mx = "[Ethereal Gem Pliers]",
			de = "[Ethereal Gem Pliers]",
			fr = "[Ethereal Gem Pliers]",
			it = "[Ethereal Gem Pliers]",
			pt = "[Ethereal Gem Pliers]",
			ru = "[Ethereal Gem Pliers]",
			ko = "[Ethereal Gem Pliers]",
			cn = "[Ethereal Gem Pliers]",
			tw = "[Ethereal Gem Pliers]",
		},
	},
	[525924] = {
		readable = "Vintage Soul Gem",
		model = 5205182,
		text = {
			en = "Vintage Soul Gem",
			es = "Gema de alma añeja",
			mx = "[Vintage Soul Gem]",
			de = "Antiker Seelenedelstein",
			fr = "Gemme d’âme de collection",
			it = "[Vintage Soul Gem]",
			pt = "[Vintage Soul Gem]",
			ru = "Антикварный самоцвет души",
			ko = "[Vintage Soul Gem]",
			cn = "[Vintage Soul Gem]",
			tw = "[Vintage Soul Gem]",
		},
	},
	[525925] = {
		readable = "Shattered Glass",
		model = 4496461,
		text = {
			en = "Shattered Glass",
			es = "[Shattered Glass]",
			mx = "[Shattered Glass]",
			de = "[Shattered Glass]",
			fr = "[Shattered Glass]",
			it = "[Shattered Glass]",
			pt = "[Shattered Glass]",
			ru = "[Shattered Glass]",
			ko = "[Shattered Glass]",
			cn = "[Shattered Glass]",
			tw = "[Shattered Glass]",
		},
	},
	[525926] = {
		readable = "Poorly Rounded Vial",
		model = 775408,
		text = {
			en = "Poorly Rounded Vial",
			es = "[Poorly Rounded Vial]",
			mx = "[Poorly Rounded Vial]",
			de = "Schlecht gerundete Phiole",
			fr = "[Poorly Rounded Vial]",
			it = "[Poorly Rounded Vial]",
			pt = "[Poorly Rounded Vial]",
			ru = "[Poorly Rounded Vial]",
			ko = "[Poorly Rounded Vial]",
			cn = "[Poorly Rounded Vial]",
			tw = "[Poorly Rounded Vial]",
		},
	},
	[525927] = {
		readable = "Dual-Function Magnifiers",
		model = 4323298,
		text = {
			en = "Dual-Function Magnifiers",
			es = "[Dual-Function Magnifiers]",
			mx = "[Dual-Function Magnifiers]",
			de = "Zweifachfunktionslupe",
			fr = "Loupe à double fonction",
			it = "[Dual-Function Magnifiers]",
			pt = "[Dual-Function Magnifiers]",
			ru = "Усилители двойного назначения",
			ko = "[Dual-Function Magnifiers]",
			cn = "[Dual-Function Magnifiers]",
			tw = "[Dual-Function Magnifiers]",
		},
	},
	[525928] = {
		readable = "Speculative Voidstorm Crystal",
		model = 1049481,
		text = {
			en = "Speculative Voidstorm Crystal",
			es = "[Speculative Voidstorm Crystal]",
			mx = "[Speculative Voidstorm Crystal]",
			de = "[Speculative Voidstorm Crystal]",
			fr = "[Speculative Voidstorm Crystal]",
			it = "[Speculative Voidstorm Crystal]",
			pt = "[Speculative Voidstorm Crystal]",
			ru = "[Speculative Voidstorm Crystal]",
			ko = "[Speculative Voidstorm Crystal]",
			cn = "[Speculative Voidstorm Crystal]",
			tw = "[Speculative Voidstorm Crystal]",
		},
	},
	[525929] = {
		readable = "Sin'dorei Masterwork Chisel",
		model = 6125159,
		text = {
			en = "Sin'dorei Masterwork Chisel",
			es = "Cincel de maestro sin'dorei",
			mx = "[Sin'dorei Masterwork Chisel]",
			de = "Meisterwerkmeißel der Sin'dorei",
			fr = "Burin à chef-d’œuvre sin’dorei",
			it = "[Sin'dorei Masterwork Chisel]",
			pt = "[Sin'dorei Masterwork Chisel]",
			ru = "Искусный син'дорайский резец",
			ko = "[Sin'dorei Masterwork Chisel]",
			cn = "[Sin'dorei Masterwork Chisel]",
			tw = "[Sin'dorei Masterwork Chisel]",
		},
	},
	[525930] = {
		readable = "Songwriter's Quill",
		model = 4494592,
		text = {
			en = "Songwriter's Quill",
			es = "[Songwriter's Quill]",
			mx = "[Songwriter's Quill]",
			de = "[Songwriter's Quill]",
			fr = "[Songwriter's Quill]",
			it = "[Songwriter's Quill]",
			pt = "[Songwriter's Quill]",
			ru = "[Songwriter's Quill]",
			ko = "[Songwriter's Quill]",
			cn = "[Songwriter's Quill]",
			tw = "[Songwriter's Quill]",
		},
	},
	[525931] = {
		readable = "Songwriter's Pen",
		model = 1850853,
		text = {
			en = "Songwriter's Pen",
			es = "Plumilla de compositor",
			mx = "[Songwriter's Pen]",
			de = "Stift des Komponisten",
			fr = "Calame de composition",
			it = "[Songwriter's Pen]",
			pt = "Caneta do Compositor",
			ru = "Ручка песенника",
			ko = "[Songwriter's Pen]",
			cn = "[Songwriter's Pen]",
			tw = "[Songwriter's Pen]",
		},
	},
	[525933] = {
		readable = "Leftover Sanguithorn Pigment",
		model = 6935636,
		text = {
			en = "Leftover Sanguithorn Pigment",
			es = "[Leftover Sanguithorn Pigment]",
			mx = "[Leftover Sanguithorn Pigment]",
			de = "[Leftover Sanguithorn Pigment]",
			fr = "[Leftover Sanguithorn Pigment]",
			it = "[Leftover Sanguithorn Pigment]",
			pt = "[Leftover Sanguithorn Pigment]",
			ru = "[Leftover Sanguithorn Pigment]",
			ko = "[Leftover Sanguithorn Pigment]",
			cn = "[Leftover Sanguithorn Pigment]",
			tw = "[Leftover Sanguithorn Pigment]",
		},
	},
})
do ObjectDB[objectID] = objectData; end
