local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[525906] = {
		readable = "Spare Expedition Torch",
		model = 5347378,
		text = {
			en = "Spare Expedition Torch",
			es = "[Spare Expedition Torch]",
			mx = "[Spare Expedition Torch]",
			de = "Ersatzexpeditionsfackel",
			fr = "Torche d’expédition de rechange",
			it = "[Spare Expedition Torch]",
			pt = "[Spare Expedition Torch]",
			ru = "[Spare Expedition Torch]",
			ko = "[Spare Expedition Torch]",
			cn = "[Spare Expedition Torch]",
			tw = "[Spare Expedition Torch]",
		},
	},
	[525907] = {
		readable = "Star Metal Deposit",
		model = 1692857,
		text = {
			en = "Star Metal Deposit",
			es = "[Star Metal Deposit]",
			mx = "[Star Metal Deposit]",
			de = "[Star Metal Deposit]",
			fr = "[Star Metal Deposit]",
			it = "[Star Metal Deposit]",
			pt = "[Star Metal Deposit]",
			ru = "[Star Metal Deposit]",
			ko = "[Star Metal Deposit]",
			cn = "[Star Metal Deposit]",
			tw = "[Star Metal Deposit]",
		},
	},
	[525908] = {
		readable = "Amani Expert's Chisel",
		model = 6125159,
		text = {
			en = "Amani Expert's Chisel",
			es = "[Amani Expert's Chisel]",
			mx = "[Amani Expert's Chisel]",
			de = "Meißel des Amaniexperten",
			fr = "Burin d’expertise amani",
			it = "[Amani Expert's Chisel]",
			pt = "[Amani Expert's Chisel]",
			ru = "[Amani Expert's Chisel]",
			ko = "[Amani Expert's Chisel]",
			cn = "[Amani Expert's Chisel]",
			tw = "[Amani Expert's Chisel]",
		},
	},
	[525909] = {
		readable = "Glimmering Void Pearl",
		model = 5309795,
		text = {
			en = "Glimmering Void Pearl",
			es = "[Glimmering Void Pearl]",
			mx = "[Glimmering Void Pearl]",
			de = "[Glimmering Void Pearl]",
			fr = "[Glimmering Void Pearl]",
			it = "[Glimmering Void Pearl]",
			pt = "[Glimmering Void Pearl]",
			ru = "[Glimmering Void Pearl]",
			ko = "[Glimmering Void Pearl]",
			cn = "[Glimmering Void Pearl]",
			tw = "[Glimmering Void Pearl]",
		},
	},
	[525910] = {
		readable = "Solid Ore Punchers",
		model = 7377919,
		text = {
			en = "Solid Ore Punchers",
			es = "Perforadores de mineral macizo",
			mx = "[Solid Ore Punchers]",
			de = "Massive Erzstanzer",
			fr = "Poinçons à minerai massif",
			it = "[Solid Ore Punchers]",
			pt = "Perfuradores de Minérios Sólidos",
			ru = "Цельнолитые перчатки рудобоя",
			ko = "[Solid Ore Punchers]",
			cn = "[Solid Ore Punchers]",
			tw = "堅固的礦石打洞機",
		},
	},
	[525911] = {
		readable = "Lost Voidstorm Satchel",
		model = 6701013,
		text = {
			en = "Lost Voidstorm Satchel",
			es = "[Lost Voidstorm Satchel]",
			mx = "[Lost Voidstorm Satchel]",
			de = "[Lost Voidstorm Satchel]",
			fr = "[Lost Voidstorm Satchel]",
			it = "[Lost Voidstorm Satchel]",
			pt = "[Lost Voidstorm Satchel]",
			ru = "[Lost Voidstorm Satchel]",
			ko = "[Lost Voidstorm Satchel]",
			cn = "[Lost Voidstorm Satchel]",
			tw = "[Lost Voidstorm Satchel]",
		},
	},
	[525912] = {
		readable = "Spelunker's Lucky Charm",
		model = 6212423,
		text = {
			en = "Spelunker's Lucky Charm",
			es = "[Spelunker's Lucky Charm]",
			mx = "Amuleto de la suerte de espeleólogo",
			de = "Glücksbringer des Höhlenforschers",
			fr = "Porte-bonheur de spéléologie",
			it = "[Spelunker's Lucky Charm]",
			pt = "Patuá da Sorte do Espeleologista",
			ru = "Спелеологический талисман на удачу",
			ko = "[Spelunker's Lucky Charm]",
			cn = "[Spelunker's Lucky Charm]",
			tw = "[Spelunker's Lucky Charm]",
		},
	},
	[525913] = {
		readable = "Miner's Guide to Voidstorm",
		model = 6025929,
		text = {
			en = "Miner's Guide to Voidstorm",
			es = "[Miner's Guide to Voidstorm]",
			mx = "[Miner's Guide to Voidstorm]",
			de = "[Miner's Guide to Voidstorm]",
			fr = "[Miner's Guide to Voidstorm]",
			it = "[Miner's Guide to Voidstorm]",
			pt = "[Miner's Guide to Voidstorm]",
			ru = "[Miner's Guide to Voidstorm]",
			ko = "[Miner's Guide to Voidstorm]",
			cn = "[Miner's Guide to Voidstorm]",
			tw = "[Miner's Guide to Voidstorm]",
		},
	},
	[525914] = {
		readable = "Artisan's Considered Order",
		model = 6025933,
		text = {
			en = "Artisan's Considered Order",
			es = "Pedido pendiente de artesano",
			mx = "Orden considerada de artesano",
			de = "Bedachter Auftrag des Kunsthandwerkers",
			fr = "Commande précieuse d’artisanat",
			it = "Ordine Ragionato dell'Artigiano",
			pt = "[Artisan's Considered Order]",
			ru = "Пересмотренное пособие ремесленника",
			ko = "[Artisan's Considered Order]",
			cn = "[Artisan's Considered Order]",
			tw = "[Artisan's Considered Order]",
		},
	},
	[525915] = {
		readable = "Haranir Leatherworking Knife",
		model = 6693152,
		text = {
			en = "Haranir Leatherworking Knife",
			es = "[Haranir Leatherworking Knife]",
			mx = "[Haranir Leatherworking Knife]",
			de = "[Haranir Leatherworking Knife]",
			fr = "[Haranir Leatherworking Knife]",
			it = "[Haranir Leatherworking Knife]",
			pt = "[Haranir Leatherworking Knife]",
			ru = "[Haranir Leatherworking Knife]",
			ko = "[Haranir Leatherworking Knife]",
			cn = "[Haranir Leatherworking Knife]",
			tw = "[Haranir Leatherworking Knife]",
		},
	},
	[525916] = {
		readable = "Haranir Leatherworking Mallet",
		model = 6693153,
		text = {
			en = "Haranir Leatherworking Mallet",
			es = "[Haranir Leatherworking Mallet]",
			mx = "[Haranir Leatherworking Mallet]",
			de = "[Haranir Leatherworking Mallet]",
			fr = "[Haranir Leatherworking Mallet]",
			it = "[Haranir Leatherworking Mallet]",
			pt = "[Haranir Leatherworking Mallet]",
			ru = "[Haranir Leatherworking Mallet]",
			ko = "[Haranir Leatherworking Mallet]",
			cn = "[Haranir Leatherworking Mallet]",
			tw = "[Haranir Leatherworking Mallet]",
		},
	},
	[525917] = {
		readable = "Patterns: Beyond the Void",
		model = 5975122,
		text = {
			en = "Patterns: Beyond the Void",
			es = "[Patterns: Beyond the Void]",
			mx = "[Patterns: Beyond the Void]",
			de = "[Patterns: Beyond the Void]",
			fr = "[Patterns: Beyond the Void]",
			it = "[Patterns: Beyond the Void]",
			pt = "[Patterns: Beyond the Void]",
			ru = "[Patterns: Beyond the Void]",
			ko = "[Patterns: Beyond the Void]",
			cn = "[Patterns: Beyond the Void]",
			tw = "[Patterns: Beyond the Void]",
		},
	},
	[525918] = {
		readable = "Bundle of Tanner's Trinkets",
		model = 6212421,
		text = {
			en = "Bundle of Tanner's Trinkets",
			es = "[Bundle of Tanner's Trinkets]",
			mx = "[Bundle of Tanner's Trinkets]",
			de = "[Bundle of Tanner's Trinkets]",
			fr = "[Bundle of Tanner's Trinkets]",
			it = "[Bundle of Tanner's Trinkets]",
			pt = "[Bundle of Tanner's Trinkets]",
			ru = "[Bundle of Tanner's Trinkets]",
			ko = "[Bundle of Tanner's Trinkets]",
		},
	},
})
do ObjectDB[objectID] = objectData; end
